package com.example.myapplication

data class GameData(
    val truths: List<String> = listOf(
        "Quelle est la chose la plus embarrassante qui vous soit arrivée ?",
        "Quelle est votre plus grande peur ?",
        "Quelle est la chose la plus folle que vous ayez faite ?",
        "Quelle est votre plus grande faiblesse ?",
        "Quelle est la chose la plus courageuse que vous ayez faite ?",
        "Quelle est votre plus grande erreur ?",
        "Quelle est la chose la plus drôle qui vous soit arrivée ?",
        "Quelle est votre plus grande réussite ?",
        "Quelle est la chose la plus difficile que vous ayez faite ?",
        "Quelle est votre plus grande déception ?",
        "Quelle est votre plus grande fierté ?",
        "Quelle est la chose la plus stupide que vous ayez faite ?",
        "Quelle est votre plus grande honte ?",
        "Quelle est la chose la plus risquée que vous ayez faite ?",
        "Quelle est votre plus grande frustration ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte ?",
        "Quelle est votre plus grande joie ?",
        "Quelle est la chose la plus difficile que vous ayez dû avouer ?",
        "Quelle est votre plus grande tristesse ?",
        "Quelle est la chose la plus excitante que vous ayez faite ?",
        "Quelle est votre plus grande colère ?",
        "Quelle est la chose la plus mémorable de votre enfance ?",
        "Quelle est votre plus grande surprise ?",
        "Quelle est la chose la plus difficile que vous ayez dû apprendre ?",
        "Quelle est votre plus grande déception amoureuse ?",
        "Quelle est la chose la plus drôle que vous ayez dite ?",
        "Quelle est votre plus grande réussite scolaire ?",
        "Quelle est la chose la plus difficile que vous ayez dû surmonter ?",
        "Quelle est votre plus grande fierté professionnelle ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur vous-même ?",
        "Quelle est votre plus grande peur pour l'avenir ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter ?",
        "Quelle est votre plus grande joie quotidienne ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur quelqu'un d'autre ?",
        "Quelle est votre plus grande frustration au travail ?",
        "Quelle est la chose la plus difficile que vous ayez dû pardonner ?",
        "Quelle est votre plus grande fierté personnelle ?",
        "Quelle est la chose la plus surprenante que vous ayez vécue ?",
        "Quelle est votre plus grande peur irrationnelle ?",
        "Quelle est la chose la plus difficile que vous ayez dû abandonner ?",
        "Quelle est votre plus grande joie de vivre ?",
        "Quelle est la chose la plus surprenante que vous ayez réalisée ?",
        "Quelle est votre plus grande frustration dans la vie ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter de vous-même ?",
        "Quelle est votre plus grande fierté familiale ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur le monde ?",
        "Quelle est votre plus grande peur pour vos proches ?",
        "Quelle est la chose la plus difficile que vous ayez dû affronter seule ?",
        "Quelle est votre plus grande joie en famille ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur l'amitié ?",
        "Quelle est votre plus grande frustration dans vos relations ?",
        "Quelle est la chose la plus difficile que vous ayez dû partager ?",
        "Quelle est votre plus grande fierté dans vos relations ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur l'amour ?",
        "Quelle est votre plus grande peur dans vos relations ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter dans une relation ?",
        "Quelle est votre plus grande joie en amour ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur vous-même en amour ?",
        "Quelle est votre plus grande frustration amoureuse ?",
        "Quelle est la chose la plus difficile que vous ayez dû surmonter en amour ?",
        "Quelle est votre plus grande fierté dans votre vie amoureuse ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur le couple ?",
        "Quelle est votre plus grande peur pour votre avenir amoureux ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter dans votre vie amoureuse ?",
        "Quelle est votre plus grande joie en couple ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur votre partenaire ?",
        "Quelle est votre plus grande frustration dans votre couple ?",
        "Quelle est la chose la plus difficile que vous ayez dû pardonner à votre partenaire ?",
        "Quelle est votre plus grande fierté dans votre couple ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur le mariage ?",
        "Quelle est votre plus grande peur pour votre mariage ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter dans votre mariage ?",
        "Quelle est votre plus grande joie dans votre mariage ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur la vie de couple ?",
        "Quelle est votre plus grande frustration dans votre vie de couple ?",
        "Quelle est la chose la plus difficile que vous ayez dû surmonter dans votre couple ?",
        "Quelle est votre plus grande fierté dans votre vie de couple ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur la parentalité ?",
        "Quelle est votre plus grande peur pour vos enfants ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter en tant que parent ?",
        "Quelle est votre plus grande joie en tant que parent ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur vos enfants ?",
        "Quelle est votre plus grande frustration en tant que parent ?",
        "Quelle est la chose la plus difficile que vous ayez dû apprendre en tant que parent ?",
        "Quelle est votre plus grande fierté en tant que parent ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur l'éducation ?",
        "Quelle est votre plus grande peur pour l'éducation de vos enfants ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter dans l'éducation de vos enfants ?",
        "Quelle est votre plus grande joie dans l'éducation de vos enfants ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur le développement des enfants ?",
        "Quelle est votre plus grande frustration dans l'éducation de vos enfants ?",
        "Quelle est la chose la plus difficile que vous ayez dû surmonter en tant que parent ?",
        "Quelle est votre plus grande fierté dans l'éducation de vos enfants ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur la vie de famille ?",
        "Quelle est votre plus grande peur pour votre famille ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter dans votre famille ?",
        "Quelle est votre plus grande joie en famille ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur vos proches ?",
        "Quelle est votre plus grande frustration dans votre famille ?",
        "Quelle est la chose la plus difficile que vous ayez dû pardonner à un membre de votre famille ?",
        "Quelle est votre plus grande fierté familiale ?",
        "Quelle est la chose la plus surprenante que vous ayez apprise sur les relations familiales ?",
        "Quelle est votre plus grande peur pour l'avenir de votre famille ?",
        "Quelle est la chose la plus difficile que vous ayez dû accepter dans votre vie familiale ?",
        "Quelle est votre plus grande joie dans votre vie familiale ?",
        "Quelle est la chose la plus surprenante que vous ayez découverte sur la vie de famille ?",
        "Quelle est votre plus grande frustration dans votre vie de famille ?",
        "Quelle est la chose la plus difficile que vous ayez dû surmonter en famille ?",
        "Quelle est votre plus grande fierté dans votre vie de famille ?"
    ),
    val dares: List<String> = listOf(
        "Faites une imitation de quelqu'un dans la pièce",
        "Chantez une chanson à haute voix",
        "Faites 10 pompes",
        "Dansez pendant 30 secondes",
        "Faites une blague à quelqu'un",
        "Faites une grimace",
        "Faites un compliment à quelqu'un",
        "Faites un tour sur vous-même",
        "Faites un bruit d'animal",
        "Faites un geste drôle",
        "Faites une danse ridicule",
        "Faites une imitation d'un animal",
        "Faites une blague à vous-même",
        "Faites un compliment à vous-même",
        "Faites une grimace drôle",
        "Faites un bruit de voiture",
        "Faites une imitation d'un personnage célèbre",
        "Faites une danse de la victoire",
        "Faites une blague à un inconnu",
        "Faites un compliment à un inconnu",
        "Faites une grimace à un inconnu",
        "Faites un bruit de machine",
        "Faites une imitation d'un sportif",
        "Faites une danse de la joie",
        "Faites une blague à un ami",
        "Faites un compliment à un ami",
        "Faites une grimace à un ami",
        "Faites un bruit de nature",
        "Faites une imitation d'un acteur",
        "Faites une danse de la tristesse",
        "Faites une blague à un membre de votre famille",
        "Faites un compliment à un membre de votre famille",
        "Faites une grimace à un membre de votre famille",
        "Faites un bruit de ville",
        "Faites une imitation d'un chanteur",
        "Faites une danse de la colère",
        "Faites une blague à un collègue",
        "Faites un compliment à un collègue",
        "Faites une grimace à un collègue",
        "Faites un bruit de fête",
        "Faites une imitation d'un politicien",
        "Faites une danse de la surprise",
        "Faites une blague à un voisin",
        "Faites un compliment à un voisin",
        "Faites une grimace à un voisin",
        "Faites un bruit de sport",
        "Faites une imitation d'un présentateur",
        "Faites une danse de la peur",
        "Faites une blague à un commerçant",
        "Faites un compliment à un commerçant",
        "Faites une grimace à un commerçant",
        "Faites un bruit de restaurant",
        "Faites une imitation d'un professeur",
        "Faites une danse de la faim",
        "Faites une blague à un serveur",
        "Faites un compliment à un serveur",
        "Faites une grimace à un serveur",
        "Faites un bruit de cuisine",
        "Faites une imitation d'un médecin",
        "Faites une danse de la santé",
        "Faites une blague à un patient",
        "Faites un compliment à un patient",
        "Faites une grimace à un patient",
        "Faites un bruit d'hôpital",
        "Faites une imitation d'un policier",
        "Faites une danse de la justice",
        "Faites une blague à un suspect",
        "Faites un compliment à un suspect",
        "Faites une grimace à un suspect",
        "Faites un bruit de commissariat",
        "Faites une imitation d'un pompier",
        "Faites une danse du courage",
        "Faites une blague à un sinistré",
        "Faites un compliment à un sinistré",
        "Faites une grimace à un sinistré",
        "Faites un bruit de caserne",
        "Faites une imitation d'un avocat",
        "Faites une danse de la défense",
        "Faites une blague à un client",
        "Faites un compliment à un client",
        "Faites une grimace à un client",
        "Faites un bruit de tribunal",
        "Faites une imitation d'un juge",
        "Faites une danse de la loi",
        "Faites une blague à un accusé",
        "Faites un compliment à un accusé",
        "Faites une grimace à un accusé",
        "Faites un bruit de cour",
        "Faites une imitation d'un journaliste",
        "Faites une danse de l'information",
        "Faites une blague à un intervieweur",
        "Faites un compliment à un intervieweur",
        "Faites une grimace à un intervieweur",
        "Faites un bruit de studio",
        "Faites une imitation d'un photographe",
        "Faites une danse de la photo",
        "Faites une blague à un modèle",
        "Faites un compliment à un modèle",
        "Faites une grimace à un modèle",
        "Faites un bruit d'appareil photo",
        "Faites une imitation d'un peintre",
        "Faites une danse de l'art",
        "Faites une blague à un spectateur",
        "Faites un compliment à un spectateur",
        "Faites une grimace à un spectateur",
        "Faites un bruit d'atelier",
        "Faites une imitation d'un sculpteur",
        "Faites une danse de la création",
        "Faites une blague à un visiteur",
        "Faites un compliment à un visiteur",
        "Faites une grimace à un visiteur",
        "Faites un bruit de galerie",
        "Faites une imitation d'un musicien",
        "Faites une danse de la musique",
        "Faites une blague à un auditeur",
        "Faites un compliment à un auditeur",
        "Faites une grimace à un auditeur",
        "Faites un bruit de concert",
        "Faites une imitation d'un danseur",
        "Faites une danse de la danse",
        "Faites une blague à un spectateur",
        "Faites un compliment à un spectateur",
        "Faites une grimace à un spectateur",
        "Faites un bruit de ballet",
        "Faites une imitation d'un acteur",
        "Faites une danse du théâtre",
        "Faites une blague à un public",
        "Faites un compliment à un public",
        "Faites une grimace à un public",
        "Faites un bruit de scène",
        "Faites une imitation d'un réalisateur",
        "Faites une danse du cinéma",
        "Faites une blague à un acteur",
        "Faites un compliment à un acteur",
        "Faites une grimace à un acteur",
        "Faites un bruit de plateau",
        "Faites une imitation d'un producteur",
        "Faites une danse de la production",
        "Faites une blague à une équipe",
        "Faites un compliment à une équipe",
        "Faites une grimace à une équipe",
        "Faites un bruit de studio",
        "Faites une imitation d'un scénariste",
        "Faites une danse de l'écriture",
        "Faites une blague à un lecteur",
        "Faites un compliment à un lecteur",
        "Faites une grimace à un lecteur",
        "Faites un bruit de bibliothèque",
        "Faites une imitation d'un écrivain",
        "Faites une danse de la littérature",
        "Faites une blague à un éditeur",
        "Faites un compliment à un éditeur",
        "Faites une grimace à un éditeur",
        "Faites un bruit de maison d'édition",
        "Faites une imitation d'un poète",
        "Faites une danse de la poésie",
        "Faites une blague à un auditeur",
        "Faites un compliment à un auditeur",
        "Faites une grimace à un auditeur",
        "Faites un bruit de récitation",
        "Faites une imitation d'un romancier",
        "Faites une danse du roman",
        "Faites une blague à un lecteur",
        "Faites un compliment à un lecteur",
        "Faites une grimace à un lecteur",
        "Faites un bruit de lecture"
    )
) 